const express = require('express')
const usersController = require('../controllers/users')
const commonMiddle = require('../middleware/common')
const route = express.Router()
const { protect, emailToken, isAdmin } = require('../middleware/auth')
const upload = require('../middleware/upload')

route.post('/', protect, usersController.insertUsers)
route.post('/login', usersController.login)
route.post('/register', commonMiddle.validation, usersController.register)
route.get('/', usersController.getUsers)
route.get('/:id', usersController.userDetail)
route.put('/:id', commonMiddle.validation, usersController.updateUsers)
route.put('/changepin/:id', usersController.changePin)
route.put('/changephone/:id', usersController.changePhone)
route.delete('/:id', protect, isAdmin, usersController.deleteUsers)
route.put('/profile-picture/:id', upload.single('profile_picture'), usersController.uploadProfilePicture)
route.get('/email-verification/:token', emailToken, usersController.setUserVerified)

module.exports = route
